version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: progress-tracking-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/progress_tracking
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - JWT_SECRET=verySecretKeyThatShouldBeAtLeast32CharactersLong
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SERVLET_CONTEXT_PATH=
    networks:
      - progress-tracking-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:14-alpine
    container_name: progress-tracking-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=progress_tracking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - progress-tracking-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: progress-tracking-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - progress-tracking-network
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres-data:
  pgadmin-data:

networks:
  progress-tracking-network:
    driver: bridge
