spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/progress_tracking
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

# jwt config
app:
  jwt:
    secret: ${JWT_SECRET:verySecretKeyThatShouldBeAtLeast32CharactersLong}
    access-token-expiration-ms: 3600000  # 1 hour
    refresh-token-expiration-ms: 604800000  # 7 days

# swagger config
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
